#! /bin/sh

#Launch Polybar on startup
$HOME/.config/polybar/launch.sh

# Start and daemonize picom
picom -b

# Set background using feh
feh --bg-fill ~/Desktop/arch.png

# Set mouse theme
xsetroot -cursor_name left_ptr

# Shortcut X HotKey Daemon
sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          10
bspc config bottom_padding	5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a "Firefox" desktop='^1' follow=on
bspc rule -a "TelegramDesktop" desktop='^10' follow=on
bspc rule -a "Thunar" desktop=^3 follow=on
