#!/bin/bash

# Launch rofi with custom configuration
rofi -show drun -sidebar-mode \
-modi run,drun,window \
-hide-scrollbar false \
-show-icons -drun-icon-theme "Dracula Icons" \
-bw 2 \
-lines 10 \
-padding 24 \
-width 40 \
-location 1 \
-xoffset 11 \
-yoffset 45 \
-columns 1

# Theming help
# color window = background, border, separator
# color normal = background, foreground, background-alt, highlight-background, highlight-foreground
# color active = background, foreground, background-alt, highlight-background, highlight-foreground
# color urgent = background, foreground, background-alt, highlight-background, highlight-foreground
