#!/usr/bin/env bash

while true; do

# Detect what kind of interface is connected
interface="$(ip link | awk '/state UP/ {print $2}')"

# Return what network is connected
ssid=$(nmcli | awk -F: '/connected to/ {print $2}' | sed 's/connected to //' )
disconnected=" 睊 Disconnected"

if [[ $interface == "e*" ]]; then
	no_network="  $ssid"; ssid="  $ssid"
else
	no_network=" 睊 $ssid"; ssid=" 直 $ssid"
fi

if (ping -c 1 archlinux.org || ping -c 1 google.com || ping -c 1 github.com) &>/dev/null; then
    echo "$ssid" ; sleep 25
elif [ "$interface" == "" ]; then
    echo "$disconnected" ; sleep 25
else
    echo "$no_network" ; sleep 25
fi

done
