#!/usr/bin/env bash

# To know the interface type ip link 
WIFI="wlp13s0"
ETHER="enp7s0"


count=0
disconnected=" Disconnected"
connected=""

ID="$(ip link | awk '/state UP/ {print $2}')"
wifi_id=$(nmcli | grep $WIFI | awk '{print $4}')
ether_id=$(nmcli | grep $ETHER | awk '{print $4}')


while true; do
    if (ping -c 1 archlinux.org || ping -c 1 google.com || ping -c 1 bitbucket.org || ping -c 1 github.com || ping -c 1 sourceforge.net) &>/dev/null; then
        if [[ $ID == e* ]]; then
            echo "$connected $ether_id" ; sleep 25
        else
            echo "$connected $wifi_id" ; sleep 25
        fi
    else
        echo "$disconnected" ; sleep 0.5
    fi
done
