# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="starlight"
DISABLE_AUTO_TITLE="true"
ENABLE_CORRECTION="true"
plugins=(git zsh-autosuggestions)
source $ZSH/oh-my-zsh.sh
export EDITOR='nvim'

# Prezto
source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Sourcing
source $HOME/.zsh/config.zsh
source $HOME/.zsh/functions.zsh

# Path
export PATH=$HOME/bin:$PATH
export PATH=$HOME/.local/bin:$PATH
