#!/usr/bin/env bash

while true; do

# Detect what kind of interface is connected
interface="$(ip link | awk '/state UP/ {print $2}' | sed -e 's/://' | head -n 1)"
eth_interface="enp7s0"

# Return what network is connected
ssid=$(nmcli | awk -F: '/connected to/ {print $2}' | sed 's/connected to //'| head -n 1)
disconnected=" 睊 Disconnected"

if [[ $interface == $eth_interface ]]; then
	no_network=" "; ssid=" "
else
	no_network=" 睊"; ssid=" 直"
fi

if (ping -c 1 archlinux.org || ping -c 1 google.com || ping -c 1 github.com) &>/dev/null; then
    echo "$ssid" ; sleep 25
elif [ "$interface" == "" ]; then
    echo "$disconnected" ; sleep 25
else
    echo "$no_network" ; sleep 25
fi

done
